// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfCQVngbNm_nDLetEUkw9aXgRGs4vgoBc',
    appId: '1:992169757551:web:08abdb71c01a68117cf69a',
    messagingSenderId: '992169757551',
    projectId: 'evently-3fcc0',
    authDomain: 'evently-3fcc0.firebaseapp.com',
    storageBucket: 'evently-3fcc0.firebasestorage.app',
    measurementId: 'G-02MRV5JFK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDYpLc50OPvSBvDVg7oIHu-fR4BQd3NRg',
    appId: '1:992169757551:android:b133ecbd357984b77cf69a',
    messagingSenderId: '992169757551',
    projectId: 'evently-3fcc0',
    storageBucket: 'evently-3fcc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALpnqDIGcep8RJEc4_L_Vgi_NLA-SHXMM',
    appId: '1:992169757551:ios:28d2d228d4d552727cf69a',
    messagingSenderId: '992169757551',
    projectId: 'evently-3fcc0',
    storageBucket: 'evently-3fcc0.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALpnqDIGcep8RJEc4_L_Vgi_NLA-SHXMM',
    appId: '1:992169757551:ios:28d2d228d4d552727cf69a',
    messagingSenderId: '992169757551',
    projectId: 'evently-3fcc0',
    storageBucket: 'evently-3fcc0.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfCQVngbNm_nDLetEUkw9aXgRGs4vgoBc',
    appId: '1:992169757551:web:568d8c4d3992972d7cf69a',
    messagingSenderId: '992169757551',
    projectId: 'evently-3fcc0',
    authDomain: 'evently-3fcc0.firebaseapp.com',
    storageBucket: 'evently-3fcc0.firebasestorage.app',
    measurementId: 'G-SNTFV0YPE9',
  );
}
